// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoutBasketball_API.Data;

namespace ScoutBasketballAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("ScoutBasketball_API.Models.Atleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.Property<string>("PhotoUrl");

                    b.Property<int>("PosicaoId");

                    b.HasKey("Id");

                    b.HasIndex("PosicaoId");

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("ScoutBasketball_API.Models.Posicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomePosicao");

                    b.HasKey("Id");

                    b.ToTable("Posicoes");
                });

            modelBuilder.Entity("ScoutBasketball_API.Models.Atleta", b =>
                {
                    b.HasOne("ScoutBasketball_API.Models.Posicao", "Posicao")
                        .WithMany("Atletas")
                        .HasForeignKey("PosicaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
